name: CI
on: push
jobs:
  build:
    name: Build Plugin
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          # TODO: - macOS-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install libnotify development headers
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libnotify-dev
      - name: Build OBS plugin
        run: |
          mkdir ./build/
          cd ./build/
          cmake ..
          cmake --build ./
